GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order pizza"
}

### 

DELETE http://localhost:3001/todo/delete/630285a3c47e3a6e474d2050

###

PUT http://localhost:3001/todo/complete/6302a5c08205a6fcf191ed3a
